---
name: ScoreFar
main: farhandevs\ScoreFar\ScoreFar
api:
- 3.0.0
version: 5.2.0
author: farhandevs
description: Add fully customizable scoreboards to your server.
virions:
- ScoreFactory
- UpdateNotifier
- ConfigUpdater
permissions:
  sh.command.sh:
    default: true
    description: Allow players to use /scorefar command.
...
